meta_product_name: "Clicks!"
meta_title: "Clicks! Make learning fun with flashcards!"
meta_description: "We help students and teachers get the most from every single class."
meta_image: "cover.png" # should exist in `app/assets/images/`
